<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= $absoluteURL ?>/assets/css/style.css">
    <title>Sonic</title>
</head>
<body>
    <nav>
        <a href="<?= $router->generate('home') ?>">Home</a>
        <a href="">Créateurs</a>
    </nav>
    <h3>Hirokazu Yasuhara</h3>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi mollitia rem iusto sint consectetur eos ab officia neque, maiores omnis eaque fuga, tempora laboriosam nulla dicta fugiat! Et iure, corporis, corrupti impedit temporibus illum tempore cumque nobis labore odit, minus maxime quaerat. Culpa, in rerum aliquid quas iusto ut quo quisquam eaque quibusdam possimus suscipit expedita assumenda adipisci quae dolor quia, temporibus dolore. Esse at a unde distinctio omnis? Deleniti aspernatur pariatur esse nisi temporibus. Officiis laboriosam voluptatibus numquam provident nisi dolores id eius quam veniam amet, odit dignissimos sed, autem aut nobis quia voluptates ipsa, deleniti ducimus ratione quaerat tempore? Labore magnam quasi delectus! Unde rerum sequi quaerat, eos quisquam asperiores officia rem necessitatibus fugiat praesentium architecto dicta amet quo, expedita vero tempora nisi! Facilis dicta, perferendis modi id fuga sit ex sed quidem dignissimos cum. Beatae eum, maxime iusto voluptates vero vitae. Esse eos praesentium hic, sint modi quam tenetur. Unde dolores eveniet, libero saepe velit obcaecati excepturi. Saepe ipsam enim nisi, soluta hic quidem quisquam doloribus! Sunt libero fugiat veritatis harum alias porro dicta, a aut repellat natus, obcaecati, vel excepturi totam voluptatum esse dolor? Maxime quam voluptatum suscipit dolorum cum consectetur, aut modi facere tenetur sunt.</p>
    <h3>Yuji Naka</h3>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi mollitia rem iusto sint consectetur eos ab officia neque, maiores omnis eaque fuga, tempora laboriosam nulla dicta fugiat! Et iure, corporis, corrupti impedit temporibus illum tempore cumque nobis labore odit, minus maxime quaerat. Culpa, in rerum aliquid quas iusto ut quo quisquam eaque quibusdam possimus suscipit expedita assumenda adipisci quae dolor quia, temporibus dolore. Esse at a unde distinctio omnis? Deleniti aspernatur pariatur esse nisi temporibus. Officiis laboriosam voluptatibus numquam provident nisi dolores id eius quam veniam amet, odit dignissimos sed, autem aut nobis quia voluptates ipsa, deleniti ducimus ratione quaerat tempore? Labore magnam quasi delectus! Unde rerum sequi quaerat, eos quisquam asperiores officia rem necessitatibus fugiat praesentium architecto dicta amet quo, expedita vero tempora nisi! Facilis dicta, perferendis modi id fuga sit ex sed quidem dignissimos cum. Beatae eum, maxime iusto voluptates vero vitae. Esse eos praesentium hic, sint modi quam tenetur. Unde dolores eveniet, libero saepe velit obcaecati excepturi. Saepe ipsam enim nisi, soluta hic quidem quisquam doloribus! Sunt libero fugiat veritatis harum alias porro dicta, a aut repellat natus, obcaecati, vel excepturi totam voluptatum esse dolor? Maxime quam voluptatum suscipit dolorum cum consectetur, aut modi facere tenetur sunt.</p>
    <h3>Naoto Ōshima</h3>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi mollitia rem iusto sint consectetur eos ab officia neque, maiores omnis eaque fuga, tempora laboriosam nulla dicta fugiat! Et iure, corporis, corrupti impedit temporibus illum tempore cumque nobis labore odit, minus maxime quaerat. Culpa, in rerum aliquid quas iusto ut quo quisquam eaque quibusdam possimus suscipit expedita assumenda adipisci quae dolor quia, temporibus dolore. Esse at a unde distinctio omnis? Deleniti aspernatur pariatur esse nisi temporibus. Officiis laboriosam voluptatibus numquam provident nisi dolores id eius quam veniam amet, odit dignissimos sed, autem aut nobis quia voluptates ipsa, deleniti ducimus ratione quaerat tempore? Labore magnam quasi delectus! Unde rerum sequi quaerat, eos quisquam asperiores officia rem necessitatibus fugiat praesentium architecto dicta amet quo, expedita vero tempora nisi! Facilis dicta, perferendis modi id fuga sit ex sed quidem dignissimos cum. Beatae eum, maxime iusto voluptates vero vitae. Esse eos praesentium hic, sint modi quam tenetur. Unde dolores eveniet, libero saepe velit obcaecati excepturi. Saepe ipsam enim nisi, soluta hic quidem quisquam doloribus! Sunt libero fugiat veritatis harum alias porro dicta, a aut repellat natus, obcaecati, vel excepturi totam voluptatum esse dolor? Maxime quam voluptatum suscipit dolorum cum consectetur, aut modi facere tenetur sunt.</p>
</body>
</html>